sonar.projectKey=bgd6051_oauth2-springboot-angular-googlesignin-poc
sonar.organization=bgd6051
sonar.host.url=https://sonarcloud.io

# Codificación
sonar.sourceEncoding=UTF-8

# Definimos los módulos (las carpetas)
sonar.modules=authorization-server,resource-server,ag-prueba-front

# --- Configuración Authorization Server ---
authorization-server.sonar.projectBaseDir=authorization-server
authorization-server.sonar.sources=src/main/java
authorization-server.sonar.tests=src/test/java
authorization-server.sonar.java.binaries=target/classes
authorization-server.sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

# --- Configuración Resource Server ---
resource-server.sonar.projectBaseDir=resource-server
resource-server.sonar.sources=src/main/java
resource-server.sonar.tests=src/test/java
resource-server.sonar.java.binaries=target/classes
resource-server.sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

# --- Configuración Frontend (Angular) ---
ag-prueba-front.sonar.projectBaseDir=ag-prueba-front
ag-prueba-front.sonar.sources=src
ag-prueba-front.sonar.tests=src
ag-prueba-front.sonar.test.inclusions=**/*.spec.ts
ag-prueba-front.sonar.exclusions=**/node_modules/**,**/*.spec.ts
ag-prueba-front.sonar.javascript.lcov.reportPaths=coverage/lcov.info