name: Pipeline de Entrega Continua (CD)

on:
  pull_request:
    branches: [develop]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Build Backend (Emulando Despliegue)
        run: |
          cd authorization-server
          chmod +x mvnw
          ./mvnw package -DskipTests
          cd ../resource-server
          chmod +x mvnw
          ./mvnw package -DskipTests
          echo "Artefactos .jar generados y listos para producción."

      - name: Build Frontend (Emulando Despliegue)
        run: |
          cd ag-prueba-front
          npm install
          npm run build
          echo "Frontend compilado. Sincronizando con servidor de estáticos..."

      - name: Confirmación de éxito
        run: echo "Entorno configurado como ${{ vars.APP_ENVIRONMENT }}"
